In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import tensorflow as tf
from keras.applications.vgg16 import preprocess_input
import csv
import os
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
import random

from sklearn.metrics import accuracy_score, confusion_matrix,precision_score,recall_score
import cv2

In [ ]:
npzfile=np.load('/content/drive/MyDrive/Cigerate/cigerate_triplet .npz')

In [ ]:
image_pair=npzfile['arr_0']
image_label=npzfile['arr_1']

In [ ]:
sample_image=[]
for i in range(len(image_pair)):
  a, p, n=image_pair[i]
  sample_image.append(cv2.resize(p, (200,200)))

In [ ]:
encoder=tf.keras.models.load_model("/content/drive/MyDrive/Cigerate/resnet_model.h5")

In [ ]:
encod_data=[]
label=[]
for i in range(len(sample_image)):
   encod_data.append(encoder.predict(preprocess_input(np.expand_dims(np.array(sample_image)[i], axis=0))))
   label.append(image_label[i])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test,indices_train,indices_test, = train_test_split(np.array(encod_data).squeeze(), np.array(label).ravel(),np.arange(len(label)), test_size=0.33, random_state=42,stratify=np.array(label).ravel())

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

for i in range(1,20,2):
    print('For k value :', i)
    print('------------------------------------')
    knn = KNeighborsClassifier(n_neighbors=i)

    knn.fit(X_train, y_train)
    pred=knn.predict(X_test)
    acc = accuracy_score(y_test, pred)
    conf_mat = confusion_matrix(y_test, pred)
    preci_macro=precision_score(y_test, pred,average='macro')
    recall_macro=recall_score(y_test, pred,average='macro')
    preci_micro=precision_score(y_test, pred,average='micro')
    recall_micro=recall_score(y_test, pred,average='micro')

    print('Accuracy',acc)
    print('conf_mat',conf_mat)
    print('precision_macro',preci_macro)
    print('Recall_macro',recall_macro)
    print('precision_micro',preci_micro)
    print('Recall_macro',recall_micro)
    print('------------------------------------')

For k value : 1
------------------------------------
Accuracy 0.9790286975717439
conf_mat [[100   0   0   0   0   0   0   0   0   0]
 [  0 329   0   0   0   0   0   0   0   0]
 [  0   0  22   0   0   0   0   0   0   0]
 [  0   0   0 134   0   0   2   0   0   0]
 [  0   0   0   0  37   0   0   0   1   0]
 [  0   0   0   0   0  59   4   0   0   0]
 [  0   0   1   1   0   2  97   0   0   2]
 [  0   0   0   0   0   0   0  64   0   0]
 [  0   0   0   0   1   0   0   0  25   0]
 [  2   0   0   0   0   2   0   0   1  20]]
precision_macro 0.9616463043452393
Recall_macro 0.9598772299035307
precision_micro 0.9790286975717439
Recall_macro 0.9790286975717439
------------------------------------
For k value : 3
------------------------------------
Accuracy 0.9735099337748344
conf_mat [[100   0   0   0   0   0   0   0   0   0]
 [  0 329   0   0   0   0   0   0   0   0]
 [  0   0  22   0   0   0   0   0   0   0]
 [  0   0   1 132   0   0   3   0   0   0]
 [  0   0   0   1  36   0   0   0   1   0]
 [ 